# Generated by Django 4.2.30 on 2026-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('density', models.DecimalField(decimal_places=2, help_text='Density in tons/m³', max_digits=5)),
                ('typical_use', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gravel Type',
                'verbose_name_plural': 'Gravel Types',
                'ordering': ['order', 'name'],
            },
        ),
    ]
